@extends('layouts.admin')

@section('title', 'Manage API Keys')

@section('content')

<div class="page-header">
    <h1>
        <span class="typcn typcn-key"></span> Manage API Keys
    </h1>
    <div>
        <a class="btn btn-sm btn-primary" href="{{ route('admin.api-keys.add') }}">
            Generate New Key
        </a>
    </div>
</div>

<p>Generate API keys as an alternative authentication when submitting confessions.</p>
<p>This is extremely useful in allowing other developers to develop solutions using NUSWhispers API without the
    hindrance of the reCAPTCHA validation.</p>
<p><b>Please be responsible in giving out API keys!</b></p>

<hr>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Key</th>
            <th>Generated by</th>
            <th>Last used</th>
            <th>Created at</th>
            <th>Action(s)</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($keys as $key)
        <tr>
            <td><code>{{ $key->key }}</code></td>
            <td>{{ $key->creator->name ?: '-' }} ({{ $key->creator->email }})</td>
            <td>{{ $key->last_used_on->diffForHumans() }}</td>
            <td>{{ $key->created_on->diffForHumans() }}</td>
            <td>
                <a class="btn btn-sm btn-danger" href="{{ route('admin.api-keys.delete', $key->getKey()) }}">
                    Delete
                </a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@endsection
