@extends('admin')

@section('content')
<form id="api-keys-search-form" class="search-form form-inline" method="get">

  <div class="page-header">
    <h1 class="page-title"><span class="typcn typcn-key"></span>API Keys Management <a href="/admin/api-keys/add" class="btn btn-sm btn-primary">Generate New Key</a></h1>

  </div>

  @include('message')

  <div class="search-filters">
    <?php echo str_replace('pagination', 'pagination pagination-sm', $keys->render()); ?>
  </div>
  
  <p>Generate API keys as an alternative authentication when submitting confessions.</p>
  <p>This is extremely useful in allowing other developers to develop solutions using NUSWhispers API without the hindrance of the reCAPTCHA validation.</p>
  
  <p><strong>Please be responsible in giving out API keys!</strong></p>

  <table id="keys-list" class="keys-list table table-striped table-hover">
    <thead>
      <tr>
          <th>Key</th>
          <th>Generated by</th>
          <th>Last used</th>
          <th>Created at</th>
          <th>Action(s)</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($keys as $key)
    <tr>
        <td><code>{{ $key->key }}</code></td>
        <td>{{ $key->creator->name ?: '-' }} ({{ $key->creator->email }})</td>
        <td>{{ $key->last_used_on->diffForHumans() }}</td>
        <td>{{ $key->created_on->diffForHumans() }}</td>
        <td>
            <a class="btn btn-sm btn-danger" href="/admin/api-keys/delete/{{ $key->getKey() }}">
                Delete
            </a>
        </td>
    </tr>
    @endforeach
    </tbody>
  </table>

  <div class="search-filters">
    <?php echo str_replace('pagination', 'pagination pagination-sm', $keys->render()); ?>
  </div>

</form><!-- #api-keys-search-form -->
@endsection
